name: GitHub Pages Deploy

on:
  push:
    branches: [main]
  pull_request:
    brahches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu_latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set-up Node
        uses: actions/setup-node@v2
        with:
          node-version: "10.x"

      - name: Install
        run: npm install

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
          with:
            branch: main
            folder: ./

